apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: polar
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: order-service
        image: order-service
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5"]
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
          requests:
              cpu: 100m
              memory: 512Mi
        ports:
        - containerPort: 7001
        env:
          - name: POLAR_CATALOG_SERVICE_URI
            value: http://catalog-service
          - name: SPRING_CONFIG_URI
            value: http://config-service
          - name: SPRING_DATASOURCE_URL
            value: r2dbc:postgresql://polar-postgres/polardb_order
          - name: SPRING_FLYWAY_URL
            value: jdbc:postgresql://polar-postgres/polardb_order
          