apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: polar
spec:
  selector:
    app: order-service
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7001
